# Generated by Django 3.0 on 2021-12-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='time',
        ),
    ]
