# Generated by Django 3.2.8 on 2021-10-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inputs',
            new_name='Input',
        ),
    ]
