# Generated by Django 3.2.8 on 2021-11-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.candidate'),
        ),
    ]
