# Generated by Django 3.2.8 on 2021-10-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_rename_inputs_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('homeUniversity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('ect', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.AddField(
            model_name='candidate',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.subjects'),
        ),
    ]
