# Generated by Django 3.2.8 on 2021-11-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_auto_20211108_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable', to='inputs.candidate'),
        ),
    ]
