# Generated by Django 3.2.8 on 2021-11-01 18:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_auto_20211027_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=2, size=None),
            preserve_default=False,
        ),
    ]
