# Generated by Django 3.0 on 2021-12-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_auto_20211214_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
