# Generated by Django 3.2.8 on 2021-11-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0004_subjects_dates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
