# Generated by Django 3.2.8 on 2021-11-01 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None),
        ),
    ]
