# Generated by Django 3.2.8 on 2021-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_alter_subject_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dates',
            field=models.DateTimeField(),
        ),
    ]
