# Generated by Django 3.2.8 on 2021-11-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0008_alter_subject_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='dates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.datecalendar'),
        ),
    ]
