# Generated by Django 3.2.8 on 2021-11-01 19:40

from django.db import migrations, models
import inputs.myFields


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0009_auto_20211101_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTheWeek', inputs.myFields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dates',
        ),
        migrations.DeleteModel(
            name='DateCalendar',
        ),
        migrations.AddField(
            model_name='subject',
            name='dates',
            field=models.ManyToManyField(to='inputs.SubjectDate'),
        ),
    ]
