# Generated by Django 3.2.8 on 2021-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0010_auto_20211101_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='subjects',
        ),
        migrations.AddField(
            model_name='candidate',
            name='subjects',
            field=models.ManyToManyField(to='inputs.Subject'),
        ),
    ]
