# Generated by Django 3.2.8 on 2021-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0011_auto_20211101_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='duration',
            field=models.TimeField(),
        ),
    ]
